//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garbage.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddVehicle()
        {
            this.vehiclesdetails = new HashSet<vehiclesdetail>();
        }
    
        public int Vehicle { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> updatedtime { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
        public string Model { get; set; }
        public string Image { get; set; }
        public Nullable<int> city { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehiclesdetail> vehiclesdetails { get; set; }
    }
}
