//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smart_garbage_management_systemEntities : DbContext
    {
        public smart_garbage_management_systemEntities()
            : base("name=smart_garbage_management_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<add_Garbage> add_Garbages { get; set; }
        public virtual DbSet<AddVehicle> AddVehicles { get; set; }
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<dumped_area> dumped_areas { get; set; }
        public virtual DbSet<dumping_detail> dumping_details { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<garbage> garbages { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<signup> signups { get; set; }
        public virtual DbSet<vehiclesdetail> vehiclesdetails { get; set; }
    }
}
