//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class garbage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public garbage()
        {
            this.Complaints = new HashSet<Complaint>();
        }
    
        public int garbage_id { get; set; }
        public int fk_user_id { get; set; }
        public string Hygiene_level { get; set; }
        public string Comment { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> fk_garbage_type { get; set; }
    
        public virtual add_Garbage add_Garbage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual signup signup { get; set; }
    }
}
