//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class signup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public signup()
        {
            this.Complaints = new HashSet<Complaint>();
            this.dumping_detail = new HashSet<dumping_detail>();
            this.feedbacks = new HashSet<feedback>();
            this.garbages = new HashSet<garbage>();
            this.vehiclesdetails = new HashSet<vehiclesdetail>();
        }
    
        public int Signup_ID { get; set; }
        public Nullable<int> fk_city_id { get; set; }
        public Nullable<int> fk_area_id { get; set; }
        public Nullable<int> fk_role_id { get; set; }
        public string username { get; set; }
        public string FatherName { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string phone_no { get; set; }
        public string gender { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public string image { get; set; }
        public string resetpassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dumping_detail> dumping_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback> feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<garbage> garbages { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehiclesdetail> vehiclesdetails { get; set; }
    }
}
