//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiclesdetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehiclesdetail()
        {
            this.dumping_detail = new HashSet<dumping_detail>();
        }
    
        public int VehicleId { get; set; }
        public Nullable<int> fk_Name { get; set; }
        public string Model { get; set; }
        public string image { get; set; }
        public Nullable<int> fk_cityid { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> Updatedtime { get; set; }
        public string Createdby { get; set; }
        public string updatedby { get; set; }
        public Nullable<int> fk_userid { get; set; }
        public Nullable<int> fk_area_id { get; set; }
    
        public virtual AddVehicle AddVehicle { get; set; }
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dumping_detail> dumping_detail { get; set; }
        public virtual signup signup { get; set; }
    }
}
